spring:
  config:
    import: 'aws-parameterstore:'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.pass}
  redis:
    host: localhost
    port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            clientSecret: ${google.client.secret}
            scope:
              - email
              - profile
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "https://ec2-3-36-48-195.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/kakao"
            client-name: Kakao
            provider: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "https://ec2-3-36-48-195.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/naver"
            client-name: Naver
            provider: naver
            scope:
              - nickname
              - email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
jwt:
  key: ${jwt.secret.key}
  access-token-expiration-minutes: 5
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    credentials:
      access-key: ${s3.access.key}
      secret-key: ${s3.secret.key}
    s3:
      bucket: edusync-refactor
    region:
      static: ap-northeast-2
    stack:
      auto: false
aws:
  paramstore:
    enabled: true
    prefix: /edusync
    name: refac
    profile-separator: _

server:
  port: 8080
  ssl:
    key-store: classpath:edusync_refac.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.pass}

logging:
  level:
    org:
      springframework:
        web: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

mail:
  address:
    admin: admin@gmail.com